services:
- type: web
  name: THERMOPAL
  env: python
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn -k eventlet -w 1 main:app"
  envVars:
    - key: SECRET_KEY
      value: your-secret-key-goes-here
  autoDeploy: true
  plan: free
  healthCheckPath: /